version: 2.1

docker-auth: &docker-auth
  auth:
    username: ${DOCKER_LOGIN}
    password: ${DOCKER_PASSWORD}

commands:
  install_protoc:
    description: Install protobuf's protoc generator
    steps:
      - run:
          command: sudo apt install -y protobuf-compiler
  compile_and_test:
    description: Compile & test protoc-gen-ts
    steps:
      - checkout
      - run:
          name: Install test dependencies
          command: cd ./tests && yarn
      - run:
          name: Compile
          command: cd ./tests && yarn compile
      - run:
          name: Generate TS code
          command: cd ./tests && yarn proto:build
      - run:
          name: Test
          command: cd ./tests && yarn test

jobs:
  build_and_test:
    docker:
      - image: circleci/golang:1.16-node
        <<: *docker-auth
    steps:
      - install_protoc
      - compile_and_test
